language: cpp
compiler:
  - gcc
  - clang
script:
  - cmake . && make && make test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - clang
    - libc++-dev
