language: cpp
script:
  - cmake . && make && make test

matrix:
  include:
    - os: linux
      compiler: clang-5.0
      install: export CC=clang-5.0 && export CXX=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:      
            - clang-5.0
            - libc++-dev

    - os: linux
      compiler: gcc-6
      install: export CC=gcc-6 && export CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

