language: cpp
script:
  - cmake . && make && make test

matrix:
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty
        packages:      
          - clang-5.0
          - libc++-dev
    env:
      - MATRIX_EVAL="export CC=clang-5.0 && export CXX=clang++-5.0" 

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
